---
- name: Install filebeat
  hosts: web_servers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy filebeat 7.14.1
      copy:
        src: ./elasticsearch_files/filebeat-7.14.1-amd64.deb
        dest: /home/grishenkovnn/

    - name: Install filebeat
      apt:
        deb: /home/grishenkovnn/filebeat-7.14.1-amd64.deb

    - name: Copy config file for filebeat
      copy:
        src: ./elasticsearch_files/filebeat.yml
        dest: /etc/filebeat
        mode: 0600
        owner: root
        group: root

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: filebeat.service
        state: started

    - name: restarted nginx
      service:
        name: nginx
        state: restarted

    - name: restarted filebeat
      service:
        name: filebeat.service
        state: restarted

    - name: Systemctl enable filebeat
      ansible.builtin.service:
        name: filebeat.service
        enabled: yes
